library(DEXSeq)

setwd("/t1-data/user/aangeles/fastaq_files/revisedcounts2")

countFiles = list.files("/t1-data/user/aangeles/fastaq_files/revisedcounts2", pattern = "CACNA1C.counts.txt$", full.names = TRUE)
basename(countFiles)

flattenedFile = "/t1-data/user/aangeles/fastaq_files/new_annotation.gff"

sampleTable=read.csv("samples_revised3.csv", row.names=1)
head(sampleTable)
dxd = DEXSeqDataSetFromHTSeq(countFiles, sampleData=sampleTable, design=~sample + exon + condition:exon, flattenedfile=flattenedFile)
dim(dxd)
dxd=estimateSizeFactors(dxd)

##Generate normalized counts for DEU file

test<-counts(dxd, normalized=T)
write.table(test, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/normalized_counts_DEXSeq.txt", sep="\t",  row.names = TRUE, col.names = TRUE)

##Make table for VGCC subunit DEU and plotting of individual genes

dxd2<-dxd[grep("ENSG00000151067", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000151067.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNA1C_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000151067", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000157388", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000157388.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNA1D_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000157388.16", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000102001", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000102001.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNA1F_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000102001.12", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000007402", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000007402.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNA2D2_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000007402.11", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000198216", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000198216.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNA1E_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000198216.11", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000007402", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000007402.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNA2D2_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000007402.11", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000157445", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000157445.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNA2D3_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000157445.14", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000153956", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000153956.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNA2D1_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000153956.15", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000148408", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000148408.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNA1B_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000148408.12", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000151062", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000151062.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNA2D4_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000151062.14", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000167535", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000167535.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNB3_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000167535.7", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000196557", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000196557.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNA1H_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000196557.12", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000067191", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000067191.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNB1_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000067191.15", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000006283", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000006283.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNA1G_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000006283.17", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000141837", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000141837.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNA1A_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000141837.19", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()

dxd2<-dxd[grep("ENSG00000100346", rownames(dxd)), ]
dim(dxd2)
dxd2=estimateDispersions(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=testForDEU(dxd2, BPPARAM=MulticoreParam(workers=16))
dxd2=estimateExonFoldChanges(dxd2, fitExpToVar="condition", BPPARAM=MulticoreParam(workers=16))
drx1=DEXSeqResults(dxd2)
head(drx1)
write.table(drx1, file="/t1-data/user/aangeles/fastaq_files/revisedcounts2/test_DEU_ENSG00000100346.txt", sep="\t", quote=F, row.names = TRUE, col.names = TRUE)
pdf("CACNA1I_DEXSeq.pdf")
plotDEXSeq(drx1, "ENSG00000100346.17", splicing = TRUE, legend=TRUE, cex.axis=1.2, cex=1.3, lwd=2 )
save(drx1, file = "/t1-data/user/aangeles/fastaq_files/revisedcounts2/iPSC_Neuron.Rdata")
dev.off()
